import { NextRequest } from 'next/server'
import { getSupabaseAdmin } from '@/lib/supabase'
import { getCache } from '@vercel/functions'
import { queryKey } from '@/lib/query-key'
import { logQuery } from '@/lib/query-log'
import { rateLimit, tooManyRequests } from '@/lib/rate-limit'
import { secretMatches } from '@/lib/auth'

export const maxDuration = 60

// Everything that reaches the model is bounded here. The body arrives from a
// browser we don't control, and `history` is echoed straight into the Anthropic
// call — unbounded, it is both a cost amplifier (one request carrying a megabyte
// of "prior turns") and a way to put arbitrary text in front of the model.
const MAX_QUERY_CHARS = 500
const MAX_HISTORY_TURNS = 12
const MAX_HISTORY_CHARS = 4_000

interface Turn { role: 'user' | 'assistant'; content: string }

function sanitizeHistory(input: unknown): Turn[] {
  if (!Array.isArray(input)) return []
  const turns: Turn[] = []
  for (const item of input.slice(-MAX_HISTORY_TURNS)) {
    if (!item || typeof item !== 'object') continue
    const { role, content } = item as { role?: unknown; content?: unknown }
    if (role !== 'user' && role !== 'assistant') continue
    if (typeof content !== 'string' || !content.trim()) continue
    turns.push({ role, content: content.slice(0, MAX_HISTORY_CHARS) })
  }
  return turns
}

// Answer cache. Parents ask the same handful of things — the dashboard's "top
// repeated questions" is the whole business case — and every repeat was paying
// for an embedding, a retrieval, and a full generation. A hit skips all three.
//
// Keyed on the canonical form of the question, so "Whos the MS principal" and
// "who is the junior high principal" share an entry, and on today's date, so a
// cached answer can never be served across a day boundary.
const CACHE_VERSION = 'v1'
// Scoped to the deployment, so shipping a fix to how answers or cards are built
// takes effect immediately instead of being masked by entries generated by the
// previous build. Caught in the act: the monogram-card fix went out and
// production kept replaying a cardless cached answer for the HS principal.
const BUILD_ID = process.env.VERCEL_DEPLOYMENT_ID ?? process.env.VERCEL_GIT_COMMIT_SHA ?? 'dev'
// Schedules move and "the next game" changes; who the principal is does not.
const VOLATILE_TTL = 15 * 60
const STABLE_TTL = 6 * 60 * 60
const VOLATILE_RE = /\b(today|tomorrow|tonight|this week|next week|game|practice|schedule|when is|what time|upcoming|closed|snow)\b/i

interface CachedAnswer {
  answer: string
  sources: { url: string; title: string }[]
  staffCards: { name: string; role: string; email: string; photo: string; campus: string }[]
  model: string
}

// Parents don't speak the website's dialect: they say "middle school" where every
// chunk says "Junior High", so the embedding has nothing to latch onto and the
// wrong campus comes back. Append the site's own wording before embedding.
const SYNONYM_EXPANSIONS: Array<[RegExp, string]> = [
  [/middle school|\bjh\b|(7th|8th|seventh|eighth)\s+grade/i, 'Junior High'],
  [/\bhs\b|freshman|sophomore|(9th|10th|11th|12th)\s+grade/i, 'High School'],
  [/\bcp\b/i, 'College Pathways'],
]

// Campus named in a query. Junior High is tested before High School so
// "junior high school" doesn't land on HS.
const CAMPUS_ALIASES: Array<[RegExp, string]> = [
  [/junior high|middle school|\bjh\b|(7th|8th|seventh|eighth) grade/i, 'Junior High'],
  [/college pathways|\bcp\b/i, 'College Pathways'],
  [/cottage/i, 'Cottage School'],
  [/high school|\bhs\b|freshman|sophomore|(9th|10th|11th|12th) grade/i, 'High School'],
  [/\beast\b/i, 'East Elementary'],
  [/\bcentral\b/i, 'Central Elementary'],
  [/\bnorth\b/i, 'North Elementary'],
]

const STAFF_QUERY_RE = /principal|teacher|teaches|counsel|dean|nurse|secretar|registrar|librarian|coach|director|superintendent|paraprofessional|\bpara\b|\baide\b|specialist|psychologist|therapist|pathologist|custodian|bookkeeper|receptionist|front office|faculty|instructor|staff|who works/i

// The name regex used for keyword retrieval is case-insensitive, so "who is the
// principal at East" captures "the principal at East" — a role question wearing a
// name's clothes. Only treat a capture as a person when it holds no role or campus
// words, otherwise the role path never gets a chance to run.
const NON_NAME_RE = /\b(principal|teacher|teaches|counsel\w*|dean|nurse|secretar\w*|registrar|librarian|coach|director|superintendent|para\w*|aide|specialist|psychologist|therapist|pathologist|custodian|bookkeeper|receptionist|office|faculty|instructor|staff|school|elementary|junior|middle|high|college|pathways|cottage|east|central|north|grade|kinder\w*|the|my|our|an?)\b/i

// Words that identify a campus rather than a role — they gate which staff cards
// are eligible, so they must not also score them.
// "what time does school start", "when does the day end", "bell schedule",
// "school hours", "dismissal time".
const BELL_SCHEDULE_RE =
  /\b(bell schedule|school hours|what time (does|do)[^?]*\b(start|begin|end|get out|let out|dismiss)|when (does|do)[^?]*\b(day|school)\b[^?]*\b(start|begin|end)|dismissal|drop.?off time|start time|end time)\b/i

const CAMPUS_WORDS = new Set(['east', 'central', 'north', 'elementary', 'junior', 'high', 'middle', 'jh', 'hs', 'cp', 'college', 'pathways', 'cottage', 'campus'])
const STAFF_STOPWORDS = new Set([
  'who', 'is', 'are', 'the', 'a', 'an', 'at', 'for', 'of', 'in', 'to', 'my', 'me', 'i',
  'what', 'whats', 'email', 'contact', 'address', 'name', 'tell', 'about', 'can', 'you',
  'give', 'list', 'please', 'need', 'and', 'with', 'does', 'do', 'their', 'there', 'his',
  'her', 'they', 'how', 'get', 'reach', 'send', 'anyone', 'someone', 'which', 'school',
  'tca', 'titans', 'info', 'information', 'phone', 'number', 'looking', 'find', 'this',
  'that', 'have', 'has', 'know', 'kid', 'kids', 'child', 'student', 'grader',
  'whos', 'whats', 'wheres', 'hows', 'here', 'new', 'current',
  // "who works at East" is a whole-directory ask, not a role — let it fall through
  // to the leadership fallback instead of matching "Social Worker"
  'work', 'works', 'working', 'worker',
])
const ORDINALS: Record<string, string> = {
  kindergarten: 'kinder', first: '1st', second: '2nd', third: '3rd', fourth: '4th',
  fifth: '5th', sixth: '6th', seventh: '7th', eighth: '8th',
}

// "teachers" and "teaches" both need to hit the role "5th Grade Teacher"
function stem(token: string): string {
  if (token.length > 4 && token.endsWith('es')) return token.slice(0, -2)
  if (token.length > 3 && token.endsWith('s')) return token.slice(0, -1)
  return token
}

// Whole-word match. Plain `includes` routed "what is the atten(dance) policy" to the
// athletics chunks, "PTO (meet)ing" likewise, and "at (least)" would read as East.
function hasTerm(text: string, term: string): boolean {
  return new RegExp(`\\b${term}\\b`, 'i').test(text)
}

// Sport words that make a question an athletics question on their own. "match" and
// "meet" are deliberately absent: as bare words they're far more often ordinary
// English ("match my student to a teacher", "PTO meeting") than sports, and real
// uses — "volleyball match", "track meet" — already carry a sport name.
const SPORT_NAMES = [
  'football', 'basketball', 'soccer', 'volleyball', 'baseball', 'softball',
  'track', 'swim', 'cross country', 'wrestling', 'lacrosse', 'tennis', 'golf', 'cheer', 'dance',
]
const SPORT_TERMS = [
  ...SPORT_NAMES,
  'scrimmage', 'game', 'games', 'tournament', 'playoff', 'playoffs', 'championship',
  'tryout', 'tryouts', 'practice', 'athletics', 'sport', 'sports',
]

const CAL_EVENT_TERMS = [
  'literacy testing', 'picture day', 'field trip', 'open house', 'back to school',
  'parent teacher', 'conference', 'curriculum night', 'grandparent', 'fall festival',
  'spring fling', 'book fair', 'spirit week', 'talent show', 'science fair',
  'kindergarten', 'early out', 'early release', 'no school', 'teacher inservice',
  'teacher workday', 'work day', 'professional development', 'pd day', 'inservice day',
  'first day', 'last day', 'winter break', 'spring break', 'fall break', 'thanksgiving',
  'christmas', 'halloween', 'valentines', 'auction', 'carnival',
  'mlk', 'martin luther king', 'presidents day', 'labor day', 'memorial day',
  'veterans day', 'columbus day', 'holiday',
  ...SPORT_TERMS,
]

// "when do the play(off)s start" and "when is the (off)ice open" both used to read as
// days-off questions, which also suppressed the athletics and calendar paths below.
const DAYS_OFF_RE = /days off|day off|school calendar|no.school days|holidays|\bdays? (out|closed)\b|when.*\b(off|closed|break)\b|schedule for the year|teacher work|workday|inservice|professional development|pd day|halloween|thanksgiving|christmas|winter break|spring break|fall break|no school/i
// Arrival and dismissal are carpool questions, not "is there school that day" questions
const CARPOOL_RE = /\b(drop[\s-]?off|pick[\s-]?up|carpool|car line|kiss and go|dismissal)\b/i

const MONTH_NAMES = ['january','february','march','april','may','june','july','august','september','october','november','december']

// TCA runs on Mountain Time; the server doesn't.
function denverNow(): Date {
  return new Date(new Date().toLocaleString('en-US', { timeZone: 'America/Denver' }))
}

// The school year runs August–June. Derived from today rather than hardcoded:
// a pinned 2026-27 array meant that come July 2027 every month would fail the
// "is it still ahead of us" test and days-off questions would quietly return
// no calendar chunks at all.
function schoolYearStart(now: Date): number {
  return now.getMonth() >= 6 ? now.getFullYear() : now.getFullYear() - 1
}

function schoolYearMonths(now: Date): Array<[number, number]> {
  const start = schoolYearStart(now)
  const months: Array<[number, number]> = []
  for (let m = 7; m <= 11; m++) months.push([m, start])      // Aug–Dec
  for (let m = 0; m <= 5; m++) months.push([m, start + 1])   // Jan–Jun
  return months
}

// "October 2025" and "October 2024" chunks were being cited next to October 2026
// for the same question. Vector search has no sense of which year is current, so
// drop calendar chunks for months that have already passed.
function isStaleCalendarChunk(chunk: { url: string; title: string }, now: Date): boolean {
  if (!/-calendar/.test(chunk.url)) return false
  const match = `${chunk.url} ${chunk.title}`.toLowerCase().match(/(january|february|march|april|may|june|july|august|september|october|november|december)[\s—-]+(20\d{2})/)
  if (!match) return false
  const month = MONTH_NAMES.indexOf(match[1])
  const year = Number(match[2])
  return year < now.getFullYear() || (year === now.getFullYear() && month < now.getMonth())
}

/* Content the school has explicitly labelled for a previous school year.
 *
 * TCA's own site mixes years: the 2026-27 supply list PDFs are posted, but the
 * grade-level pages still describe the 2025-26 ones, and the band supply list
 * on the site is labelled 2023-24. Both end up in the corpus and nothing in a
 * cosine score says which is current — so a parent asking what to buy could be
 * handed last year's list.
 *
 * Only labels attached to a *deliverable* count. "Supply List 2025-26" is a
 * stale answer; "the Healthy School Meals program began in the 2023-24 school
 * year" is a true statement about the past and stays. That distinction is the
 * whole point of the noun list below — a bare year-marker match would delete
 * ordinary prose.
 *
 * The cutoff is derived from the current school year rather than hardcoded, so
 * this ages forward on its own every August instead of needing a yearly edit.
 */
const DELIVERABLE =
  String.raw`(?:supply list|calendar|dates|schedule|handbook|form|training|packet|menu|roster|fee list|reading list)`

const DATED_DELIVERABLE = new RegExp(
  // "Supply List 2025-26" / "2025-26 Music Dates" — the label rides with the thing.
  String.raw`${DELIVERABLE}[^.\n]{0,80}?\b(20\d{2})-(\d{2})\b` +
    '|' +
    String.raw`\b(20\d{2})-(\d{2})\b[^.\n]{0,80}?${DELIVERABLE}` +
    '|' +
    // "School Year: 2025-26" as an explicit field label. Word order is what
    // separates this from prose — a label puts the noun first ("School Year:
    // 2025-26"), a sentence puts the year first ("began in the 2023-24 school
    // year"), and only the former is a claim about what currently applies.
    String.raw`school\s+year\W{0,6}\b(20\d{2})-(\d{2})\b`,
  'i'
)

function isPriorSchoolYearChunk(chunk: { content?: string }, now: Date): boolean {
  const content = chunk.content
  if (!content) return false
  const m = content.match(DATED_DELIVERABLE)
  if (!m) return false
  // Whichever alternation branch fired, the start year is the first defined group.
  const startYear = Number(m[1] ?? m[3] ?? m[5])
  return Number.isFinite(startYear) && startYear < schoolYearStart(now)
}

const CALENDAR_CAMPUS_MAP: Record<string, string> = {
  'east': 'east-elementary-calendar',
  'central': 'central-elementary-calendar',
  'north': 'north-elementary-calendar',
  'junior high': 'junior-high-calendar',
  'jh': 'junior-high-calendar',
  'high school': 'high-school-calendar',
  'college pathways': 'college-pathways-calendar',
  'cp': 'college-pathways-calendar',
}

export async function POST(req: NextRequest) {
  const requestStart = Date.now()

  // 20 questions a minute is far past what a parent does and far below what a
  // script does. The generous ceiling is deliberate: the identity is an IP, a
  // whole school on one network shares it, and locking out a real family is a
  // worse outcome than letting an abuser through a little longer.
  const limit = await rateLimit(req, { name: 'search', limit: 20, windowMs: 60_000 })
  if (!limit.ok) {
    return tooManyRequests(limit, 'Too many questions in a row — give it a moment and try again.')
  }

  const now = denverNow()
  const nowYear = now.getFullYear()
  const nowMonth = now.getMonth()
  const schoolYearLabel = `${schoolYearStart(now)}-${String(schoolYearStart(now) + 1).slice(2)}`

  const body = await req.json().catch(() => null)
  if (!body || typeof body !== 'object') {
    return Response.json({ error: 'Invalid request' }, { status: 400 })
  }
  const rawQueryInput = (body as { rawQuery?: unknown }).rawQuery
  const queryInput = (body as { query?: unknown }).query
  if (typeof queryInput !== 'string' || !queryInput.trim()) {
    return Response.json({ error: 'Query required' }, { status: 400 })
  }
  const query = queryInput.trim().slice(0, MAX_QUERY_CHARS)
  const rawQuery = typeof rawQueryInput === 'string' ? rawQueryInput.trim().slice(0, MAX_QUERY_CHARS) : query
  const history = sanitizeHistory((body as { history?: unknown }).history)
  const debug = (body as { debug?: unknown }).debug === true

  const encoder = new TextEncoder()
  const send = (obj: unknown) => encoder.encode(JSON.stringify(obj) + '\n')
  const loggedQuery = (rawQuery ?? query).trim().slice(0, 500)

  // Follow-ups depend on what was said earlier, so only standalone questions are
  // cacheable. Debug runs bypass the cache so measurements reflect real retrieval.
  const cacheable = !debug && history.length === 0
  const cacheKey = `answer:${CACHE_VERSION}:${BUILD_ID}:${now.toISOString().slice(0, 10)}:${queryKey(query)}`
  const cache = getCache()

  if (cacheable) {
    let hit: CachedAnswer | undefined
    try {
      hit = await cache.get(cacheKey) as CachedAnswer | undefined
    } catch { /* cache unavailable — answer the question the slow way */ }

    if (hit?.answer) {
      // `model` records who originally generated this answer, not 'cache' —
      // a cached Sonnet answer is still a Sonnet answer, and cache_hit is what
      // says it cost nothing this time round.
      logQuery(getSupabaseAdmin(), {
        query: loggedQuery,
        had_results: true,
        source_count: hit.sources.length,
        top_similarity: null,
        model: hit.model ?? 'cache',
        latency_ms: Date.now() - requestStart,
        answer: hit.answer,
        sources: hit.sources,
        cache_hit: true,
        input_tokens: 0,
        output_tokens: 0,
      })

      const cachedStream = new ReadableStream({
        start(controller) {
          controller.enqueue(send({ type: 'sources', sources: hit.sources }))
          if (hit.staffCards?.length) controller.enqueue(send({ type: 'staffCards', staffCards: hit.staffCards }))
          controller.enqueue(send({ type: 'text', text: hit.answer }))
          controller.enqueue(send({ type: 'done' }))
          controller.close()
        },
      })
      return new Response(cachedStream, { headers: { 'Content-Type': 'application/x-ndjson', 'x-tca-cache': 'hit' } })
    }
  }

  const [{ VoyageAIClient }, { default: Anthropic }] = await Promise.all([
    import('voyageai'),
    import('@anthropic-ai/sdk'),
  ])

  const voyage = new VoyageAIClient({ apiKey: process.env.VOYAGE_API_KEY })
  const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY })
  const supabase = getSupabaseAdmin()

  // Augment retrieval query with last user turn so follow-up questions inherit context
  const lastUserMsg = history.filter(m => m.role === 'user').slice(-1)[0]?.content ?? ''
  const baseQuery = lastUserMsg ? `${lastUserMsg} ${query}` : query
  const expansions = SYNONYM_EXPANSIONS.filter(([re]) => re.test(baseQuery)).map(([, term]) => term)
  const retrievalQuery = expansions.length ? `${baseQuery} ${expansions.join(' ')}` : baseQuery
  const embeddingRes = await voyage.embed({ input: [retrievalQuery.slice(0, 16000)], model: 'voyage-3-lite' })
  const queryEmbedding = embeddingRes.data![0].embedding!

  const { data: chunks, error } = await supabase.rpc('match_chunks', {
    query_embedding: queryEmbedding,
    match_count: 16,
  })

  if (error) {
    // The database's own words ("relation … does not exist", column names, the
    // failing filter) are a map of the schema. Keep them in the server log.
    console.error('match_chunks failed:', error.message)
    return Response.json({ error: 'Search is temporarily unavailable.' }, { status: 500 })
  }

  // Keyword fallback: name-based queries may not score high on vector search
  // because staff directories contain 50-90 names and the embedding is diluted.
  // Handles: "who is Sean Shields", "Mr. Walters", "Mrs. Smith", "tell me about Coach Jones"
  type Chunk = { url: string; title: string; content: string; similarity: number }

  // Trigram similarity in JS — same algorithm as pg_trgm
  function trigramSimilarity(a: string, b: string): number {
    const trigrams = (s: string) => {
      const padded = `  ${s.toLowerCase()}  `
      const set = new Set<string>()
      for (let i = 0; i < padded.length - 2; i++) set.add(padded.slice(i, i + 3))
      return set
    }
    const ta = trigrams(a), tb = trigrams(b)
    let shared = 0
    for (const t of ta) if (tb.has(t)) shared++
    return (2 * shared) / (ta.size + tb.size)
  }

  let keywordChunks: Chunk[] = []
  const nameMatch =
    query.match(/who\s+is\s+(?:mr\.?|mrs\.?|ms\.?|miss\.?|dr\.?|coach\.?)?\s*([A-Z][a-z]+(?:\s+[A-Z][a-z]+)*)/i) ||
    query.match(/(?:mr\.?|mrs\.?|ms\.?|miss\.?|dr\.?|coach\.?)\s+([A-Z][a-z]+)/i) ||
    query.match(/(?:about|find|contact|email)\s+(?:mr\.?|mrs\.?|ms\.?|miss\.?|dr\.?|coach\.?)?\s*([A-Z][a-z]+(?:\s+[A-Z][a-z]+)+)/i)
  if (nameMatch) {
    const name = nameMatch[1].trim()
    // Exact match first
    const { data: exactRows } = await supabase
      .from('page_chunks')
      .select('url, title, content')
      .ilike('url', '%staff-directory%')
      .ilike('content', `%${name}%`)
      .limit(8)
    keywordChunks = (exactRows ?? []).map(c => ({ ...c, similarity: 0.6 }))

    // If exact match found nothing, try fuzzy: fetch all staff chunks and score by trigram similarity
    if (keywordChunks.length === 0) {
      const { data: allStaffRows } = await supabase
        .from('page_chunks')
        .select('url, title, content')
        .ilike('url', '%staff-directory%')
        .limit(60)
      // Split searched name into parts so "Matt Brunk" scores "Matt"↔"Matthew" and "Brunk"↔"Brunk"
      const nameParts = name.toLowerCase().split(/\s+/).filter((p: string) => p.length >= 3)
      const fuzzyMatches = (allStaffRows ?? [])
        .map(c => {
          const words = c.content.match(/[A-Z][a-z]{2,}/g) ?? []
          const partScores = nameParts.map((part: string) =>
            Math.max(0, ...words.map((w: string) => trigramSimilarity(part, w.toLowerCase())))
          )
          const avgScore = partScores.length ? partScores.reduce((a: number, b: number) => a + b, 0) / partScores.length : 0
          return { ...c, similarity: avgScore }
        })
        .filter(c => c.similarity >= 0.4)
        .sort((a, b) => b.similarity - a.similarity)
        .slice(0, 8)
      keywordChunks = fuzzyMatches
    }
  }

  /* Exact-phrase anchor for named things.
   *
   * Found by find-denials.mjs: "when does Titans for Christ meet" and "does TCA
   * have a Titans for Christ" both came back with a flat "I don't have
   * information about that", while the club sits in the HS student
   * organizations PDF with its meeting day and room.
   *
   * The cause is not rarity — "Creative Writing Club" is in exactly one chunk
   * too and answers fine. It is collision. "Titans" appears in 283 of 2,242
   * chunks because it is the mascot and the domain name, so the embedding of
   * "Titans for Christ" is dominated by the generic-school-branding direction
   * and retrieval returns homepages and the fundraising page. The one chunk
   * that actually names the club never places.
   *
   * An embedding cannot easily be talked out of this, but exact text can: if a
   * multi-word phrase from the question appears verbatim in only a few chunks,
   * those chunks are about that thing, whatever the vectors think. This is
   * deliberately general rather than a list of club names — the same trap waits
   * for any program, award or event whose name reuses common school vocabulary
   * ("Titan Club", "Classical Cup", "North Star Award"). */
  const PHRASE_STOP = new Set(['the', 'a', 'an', 'is', 'are', 'was', 'were', 'do', 'does', 'did', 'when', 'what',
    'where', 'who', 'whom', 'how', 'why', 'which', 'at', 'in', 'on', 'for', 'of', 'to', 'and', 'or', 'my', 'our',
    'their', 'there', 'tca', 'school', 'have', 'has', 'had', 'can', 'i', 'me', 'we', 'you', 'it', 'that', 'this',
    'be', 'with', 'about', 'any', 'get', 'go', 'us', 'from', 'if', 'so', 'll', 's'])

  const phraseWords = query.toLowerCase().replace(/[^\w\s'’-]/g, ' ').split(/\s+/).filter(Boolean)
  const candidates: string[] = []
  // Longest first: "titans for christ meet" is tried before "titans for christ",
  // and a longer phrase that matches is stronger evidence than a shorter one.
  for (let len = 4; len >= 2 && candidates.length < 8; len--) {
    for (let i = 0; i + len <= phraseWords.length; i++) {
      const slice = phraseWords.slice(i, i + len)
      // Anchoring on a phrase that opens or closes with a filler word matches
      // sentence noise rather than a name.
      if (PHRASE_STOP.has(slice[0]) || PHRASE_STOP.has(slice[len - 1])) continue
      if (!slice.some(w => !PHRASE_STOP.has(w) && w.length >= 3)) continue
      candidates.push(slice.join(' '))
    }
  }

  if (candidates.length) {
    const found = await Promise.all(candidates.map(async phrase => {
      /* Cap at 9 so a phrase matching more than 8 chunks is recognised as
       * ordinary vocabulary and skipped — an anchor is only justified when the
       * phrase actually pins down a small set of pages. */
      const { data } = await supabase
        .from('page_chunks')
        .select('url, title, content')
        .ilike('content', `%${phrase.replace(/[%_]/g, ' ')}%`)
        .limit(9)
      return { phrase, rows: data ?? [] }
    }))

    // Longest phrase that is distinctive enough to be worth anchoring on.
    const best = found.find(f => f.rows.length > 0 && f.rows.length <= 8)
    if (best) {
      // Below the 0.90 athletics anchor, above the 0.68 event net: an exact
      // multi-word match is strong evidence, but a live schedule still wins.
      keywordChunks = [...keywordChunks, ...best.rows.map(c => ({ ...c, similarity: 0.88 }))]
    }
  }

  // Staff question about a named campus — resolved here rather than left to the
  // embedding. Every campus has near-identical "<Campus> — <Category>" chunks
  // competing for the top-16 slots, so "who's the middle school principal" can
  // come back with Central Elementary's leadership and nothing from JH.
  const rawName = nameMatch?.[1]?.trim() ?? ''
  const personName = rawName && !NON_NAME_RE.test(rawName) ? rawName : null
  const wantCampus = CAMPUS_ALIASES.find(([re]) => re.test(query))?.[1] ?? null
  const roleTokens: string[] = query
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, ' ')
    .split(/\s+/)
    .map((t: string) => ORDINALS[t] ?? t)
    .filter((t: string) => t.length > 1 && !STAFF_STOPWORDS.has(t) && !CAMPUS_WORDS.has(t))

  if (!personName && wantCampus && STAFF_QUERY_RE.test(query)) {
    // Pull the campus chunks that actually mention the role asked about; fall back
    // to that campus's leadership for broad "who works at X" asks.
    const roleAnchor = roleTokens.find(t => t.length > 2)
    const anchorQuery = supabase
      .from('page_chunks')
      .select('url, title, content')
      .ilike('url', '%staff-directory%')
      .ilike('title', `${wantCampus} — %`)
    const { data: campusRows } = roleAnchor
      ? await anchorQuery.ilike('content', `%${stem(roleAnchor)}%`).limit(4)
      : await anchorQuery.ilike('title', '%Leadership%').limit(2)
    keywordChunks = [...keywordChunks, ...(campusRows ?? []).map(c => ({ ...c, similarity: 0.7 }))]
  }


  /* "What time does school start / end" — anchored rather than left to the
   * embedding.
   *
   * The high school bell schedule lives on the campus homepage, in a chunk that
   * also carries the address, phone, fax and office hours. Against "what time
   * does the high school day end" that chunk did not make the top 40 vector
   * hits, while the answer — SEVENTH: 2:10pm - 3:00pm — sat inside it. The
   * question is one of the most common a parent asks and the content is
   * unmistakable, so it is matched on the words rather than the vector.
   *
   * Campus-scoped when the question names one. Without that, "what time does
   * the high school day end" pulled College Pathways' schedule, which ends at a
   * different time, and the answer alternated between 3:00 and 3:10 run to run.
   */
  if (BELL_SCHEDULE_RE.test(query)) {
    const bellQuery = supabase
      .from('page_chunks')
      .select('url, title, content')
      .ilike('content', '%BELL SCHEDULE%')
    const scoped = wantCampus ? bellQuery.ilike('title', `%${wantCampus}%`) : bellQuery
    const { data: bellRows } = await scoped.limit(4)
    keywordChunks = [...keywordChunks, ...(bellRows ?? []).map(c => ({ ...c, similarity: 0.75 }))]
  }


  /* Named school events — homecoming, spirit week, picture day, grandparents' day.
   *
   * These lose to the embedding twice over. A named event is usually one line
   * inside a long schedule chunk, so its signal is diluted to nothing, and any
   * chunk actually titled for it wins outright and hides the rest. Asked "when
   * is homecoming", retrieval returned the Homecoming Dance chunk at 0.379 and
   * put the football schedule carrying "TCA vs D'Evelyn: HOMECOMING" at #30 and
   * #38 — outside the sixteen the RPC returns, so the game never reached the
   * model at all and the answer named only the dance.
   *
   * Homecoming is a game on Friday and a dance on Saturday. Answering one and
   * omitting the other is how a parent misses the game.
   *
   * Matched on content across the event sources, so an event mentioned inside a
   * schedule is found the same way one with its own chunk is.
   */
  const eventTerms = query
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, ' ')
    .split(/\s+/)
    .filter(t => t.length >= 5 && !STAFF_STOPWORDS.has(t) && !CAMPUS_WORDS.has(t))
  if (eventTerms.length) {
    /* Asked per source, not once across all of them.
     *
     * A single query with one limit lets whichever source has the most rows
     * take every slot. Searching '%cross%' across all event sources returned
     * eight chunks, every one of them GoBound or TeamReach, so the Landsharks
     * page — the only place elementary cross country exists — was never
     * reached. The app told a parent whose child is signed up that "cross
     * country is not offered at the elementary level".
     *
     * A small budget per source means a term present in a small source still
     * surfaces it. They run concurrently, so this costs latency once, not once
     * per source.
     */
    const EVENT_SOURCES = [
      'url.ilike.%gobound%',
      'url.ilike.%teamreach%',
      'url.ilike.%landsharks%',
      'url.ilike.%-calendar%',
      'url.ilike.%tcatitans.org/calendar%',
      'url.ilike.newsletter://%',
    ]
    const eventRows = await Promise.all(
      eventTerms.slice(0, 2).flatMap(term =>
        EVENT_SOURCES.map(src =>
          supabase
            .from('page_chunks')
            .select('url, title, content')
            .or(src)
            .ilike('content', `%${term}%`)
            .limit(3)
            .then(r => r.data ?? [])
        )
      )
    )
    // Below the athletics anchor's 0.90 — these are a widening of the net, not
    // a statement that this is the answer.
    keywordChunks = [...keywordChunks, ...eventRows.flat().map(c => ({ ...c, similarity: 0.68 }))]
  }

  // Broad "days off" queries — pull monthly calendar chunks for the current school year.
  // Only include months from the current month onward so the AI isn't confused by past events.
  const daysOffQuery = DAYS_OFF_RE.test(query) && !CARPOOL_RE.test(query)
  if (daysOffQuery) {
    const campusKey = Object.keys(CALENDAR_CAMPUS_MAP).find(k => hasTerm(query, k))
    const urlFilter = campusKey ? `%${CALENDAR_CAMPUS_MAP[campusKey]}%` : '%-calendar%'

    const futureMonthSlugs = schoolYearMonths(denverNow())
      .filter(([m, y]) => y > nowYear || (y === nowYear && m >= nowMonth))
      .map(([m, y]) => `%${MONTH_NAMES[m]}-${y}`)

    // One query for every campus × every remaining month of the school year.
    //
    // This used to be a query per month per campus — up to 33 separate round
    // trips to Supabase before the model saw a single word, all of them on the
    // critical path of "when is the next day off". They're now a single
    // statement: the months become one OR group, the campuses another, and
    // Postgres does the intersecting.
    //
    // High School is the canonical source for school-wide no-school days;
    // East and Junior High are added for campus-specific events when the parent
    // didn't name a campus.
    const campusFilters = campusKey
      ? [urlFilter]
      : ['%high-school-calendar%', '%east-elementary-calendar%', '%junior-high-calendar%']

    const { data: daysOffRows } = await supabase
      .from('page_chunks')
      .select('url, title, content')
      .or(campusFilters.map(f => `url.ilike.${f}`).join(','))
      .or(futureMonthSlugs.map(s => `url.ilike.${s}`).join(','))
      .order('url', { ascending: true })
      .limit(120)

    // The per-month `.limit(1)` the fan-out used to give is reproduced here:
    // one chunk per calendar page, so a long month can't crowd out the rest.
    const seenCalendarUrls = new Set<string>()
    const daysOffChunks = (daysOffRows ?? [])
      .filter(c => {
        if (seenCalendarUrls.has(c.url)) return false
        seenCalendarUrls.add(c.url)
        return true
      })
      .map(c => ({ ...c, similarity: 0.72 }))
    keywordChunks = [...keywordChunks, ...daysOffChunks]
  }

  const isSportsQuery = !daysOffQuery && SPORT_TERMS.some(t => hasTerm(query, t))
  const calTermMatch = !daysOffQuery ? CAL_EVENT_TERMS.find(t => hasTerm(query, t)) : undefined

  // Named sports only (excludes generic words like "game"/"practice"/"tournament") — used to
  // anchor the specific per-team chunk by title. There are 60+ near-identically-worded
  // "TCA Athletics — <Sport> <Level> (<Gender>)" chunks competing for the vector search's
  // top-16 slots, so whether e.g. "Boys Track & Field Junior High" makes the cut for a plain
  // "when does track start" query is essentially a coin flip — the same query can surface it
  // one run and miss it the next. Anchor it by keyword the same way the Upcoming chunk is
  // anchored, instead of leaving it to embedding-ranking luck.
  const matchedSport = SPORT_NAMES.find(t => hasTerm(query, t))

  if (isSportsQuery) {
    // Always anchor sports queries with the GoBound upcoming chunk — it's the authoritative
    // aggregated view of all TCA athletics for the next 30 days with exact times.
    // Give it the highest priority so it wins over TeamReach or sport-specific chunks.
    // Fetch both GoBound upcoming chunks by exact title — avoids # encoding issues in ILIKE
    const [{ data: gbUpcoming }, { data: gbSchedule }, sportChunks] = await Promise.all([
      supabase.from('page_chunks').select('url, title, content').eq('title', 'TCA Athletics — Upcoming').limit(1),
      supabase.from('page_chunks').select('url, title, content').eq('title', 'TCA Athletics & Activities — Upcoming Schedule').limit(1),
      matchedSport
        ? supabase.from('page_chunks').select('url, title, content').ilike('title', 'TCA Athletics%').ilike('title', `%${matchedSport}%`).limit(20)
        : Promise.resolve({ data: [] }),
    ])
    const gbChunks = [...(gbUpcoming ?? []), ...(gbSchedule ?? [])].map(c => ({ ...c, similarity: 0.90 }))
    // Below the Upcoming anchor's 0.90 (so the 30-day view still wins on recency) but above
    // the 0.50 source-display threshold, so the sport-specific chunk always makes it into
    // context and is cited as a source.
    const sportSpecificChunks = (sportChunks.data ?? []).map(c => ({ ...c, similarity: 0.82 }))
    keywordChunks = [...gbChunks, ...sportSpecificChunks, ...keywordChunks]
  }

  if (calTermMatch && !isSportsQuery) {
    // Non-sports calendar keyword — search campus calendars
    const campusKey = Object.keys(CALENDAR_CAMPUS_MAP).find(k => hasTerm(query, k))
    const urlFilter = campusKey ? `%${CALENDAR_CAMPUS_MAP[campusKey]}%` : '%-calendar%'
    const { data: calRows } = await supabase
      .from('page_chunks')
      .select('url, title, content')
      .ilike('url', urlFilter)
      .ilike('content', `%${calTermMatch}%`)
      .order('url', { ascending: true })
      .limit(60)
    // Ordering is alphabetical by URL, so last year's months (…-april-2025) crowd
    // out this year's. Over-fetch, drop the stale ones, then take the top 20.
    const calChunks = (calRows ?? [])
      .filter(c => !isStaleCalendarChunk(c, now))
      .slice(0, 20)
      .map(c => ({ ...c, similarity: 0.65 }))
    keywordChunks = [...keywordChunks, ...calChunks]
  }

  // Merge: vector results first, then any keyword-only hits not already included.
  // Last year's calendar months are dropped here rather than at each fetch site,
  // so vector hits are covered too — they're the ones that surfaced October 2024
  // alongside October 2026 for the same question.
  /* Vector hits far below the best one are noise, not context.
   *
   * match_chunks is asked for 16 and returns 16 whatever the scores look like,
   * so a query with one strong match arrives with fifteen weak ones attached.
   * "When is homecoming" is the clearest case: the right chunk ranks first at
   * 0.380 and is followed by Cottage School Program, College Pathways March
   * 2027 and a dozen more at ~0.30 — a 133-character answer inside an
   * 8,625-character context that is almost entirely unrelated.
   *
   * Measured over ten representative questions, dropping anything more than
   * 0.08 below the top hit removes 46% of chunks and 51% of context. Since
   * input is 96% of what this app spends, that is most of a per-query bill.
   *
   * The floor of eight is what keeps this safe. "What are the supply lists"
   * genuinely needs many sources — one per grade and campus — and a bare margin
   * cut it to two. Keyword-anchored chunks are merged in afterwards and are
   * never subject to this: those are deliberate retrievals, not vector guesses.
   */
  const MIN_VECTOR_CHUNKS = 8
  const RELEVANCE_MARGIN = 0.08
  const vectorHits = (chunks ?? []) as Chunk[]
  const bestScore = vectorHits.length ? vectorHits[0].similarity : 0
  const relevant = vectorHits.length <= MIN_VECTOR_CHUNKS
    ? vectorHits
    : vectorHits.filter((c, i) => i < MIN_VECTOR_CHUNKS || bestScore - c.similarity <= RELEVANCE_MARGIN)

  /* One chunk per URL, however many anchors asked for it.
   *
   * Several anchors run for one question — athletics, sport-specific, named
   * event, campus — and they overlap heavily. Asked "is there football practice
   * next week", the context held 43 chunks of which 27 were anchor duplicates:
   * fifteen identical copies of "TCA Athletics — Upcoming" and six of Girls
   * Flag Football. The one chunk that answered the question sat first and was
   * buried under repetition of chunks that did not.
   *
   * Deduplicating on url alone was not enough because only the vector hits were
   * being checked against; the anchors were never compared with each other.
   */
  const seenUrls = new Set(relevant.map((c: Chunk) => c.url))
  const dedupedKeyword: Chunk[] = []
  for (const c of keywordChunks) {
    if (seenUrls.has(c.url)) continue
    seenUrls.add(c.url)
    dedupedKeyword.push(c)
  }

  const merged: Chunk[] = [
    ...relevant,
    ...dedupedKeyword,
    // Applied here rather than at ingest so it covers what is already stored,
    // and so the cutoff moves with the school year instead of being baked into
    // whatever the corpus happened to look like on crawl day.
  ].filter(c => !isStaleCalendarChunk(c, now) && !isPriorSchoolYearChunk(c, now))

  if (!merged?.length) {
    const noResultsAnswer = "I couldn't find information about that on the TCA website. Try rephrasing your question or visit tcatitans.org directly."
    logQuery(supabase, {
      query: loggedQuery,
      had_results: false,
      source_count: 0,
      top_similarity: null,
      model: null,
      latency_ms: Date.now() - requestStart,
      answer: noResultsAnswer,
      sources: [],
      cache_hit: false,
    })

    const stream = new ReadableStream({
      start(controller) {
        controller.enqueue(send({ type: 'sources', sources: [] }))
        controller.enqueue(send({ type: 'text', text: noResultsAnswer }))
        controller.enqueue(send({ type: 'done' }))
        controller.close()
      }
    })
    return new Response(stream, { headers: { 'Content-Type': 'application/x-ndjson' } })
  }

  // Staff photo cards — shown for any staff question, not just "who is <Name>".
  // Three shapes are handled: a specific person ("who is Mr. Walters"), a role
  // ("who's the principal at East"), and a group ("5th grade teachers at North").
  // Capped so a whole grade level doesn't bury the answer.
  const MAX_STAFF_CARDS = 6
  type StaffCard = { name: string; role: string; email: string; photo: string; campus: string }

  // Both staff chunk shapes: per-category lines ("Role: Name — email [photo:url]")
  // and the campus summary chunk ("Role: Name (email) [photo:url], Name2 (...)").
  function extractStaffEntries(chunk: Chunk): StaffCard[] {
    const lines = chunk.content.split('\n')
    const campus = (lines[0] ?? '').split('—')[0].replace(/staff directory/i, '').replace(/[:\s]+$/, '').trim()
    const entries: StaffCard[] = []
    for (const line of lines.slice(1)) {
      const colon = line.indexOf(':')
      if (colon < 1) continue
      const role = line.slice(0, colon).trim()
      const rest = line.slice(colon + 1)
      if (!role || role.startsWith('(')) continue

      const single = rest.match(/^\s*(.+?)\s+—\s+([\w.]*@tcatitans\.org)\s*(?:\[photo:([^\]]+)\])?\s*$/)
      if (single) {
        entries.push({ name: single[1].trim(), role, email: single[2], photo: single[3] ?? '', campus })
        continue
      }
      for (const m of rest.matchAll(/([^,()]+?)\s+\(([\w.]*@tcatitans\.org|)\)\s*(?:\[photo:([^\]]+)\])?/g)) {
        const name = m[1].trim()
        if (name) entries.push({ name, role, email: m[2] ?? '', photo: m[3] ?? '', campus })
      }
    }
    return entries
  }

  // Who deserves a face is a judgment call, and there's already something smart
  // in this request making it: the model writing the answer. So instead of
  // guessing from the question with keyword scores — which is what put six
  // administrators above "I don't know who the football coach is", and Director
  // of Bands under "who is the athletic director" — we index everyone who
  // appears in the retrieved staff chunks, and after the answer is written we
  // show cards for exactly the people it named, in the order it named them.
  // Cards can no longer contradict the answer, because the answer chooses them.
  const staffIndex = new Map<string, StaffCard>()
  for (const chunk of merged) {
    if (!chunk.url.includes('staff-directory')) continue
    for (const entry of extractStaffEntries(chunk)) {
      // Staff without a headshot are indexed too — about 12% of the directory
      // has a placeholder image rather than a photo, including the High School
      // principal. The card still carries their role, campus and email, so the
      // UI shows a monogram instead of dropping the person entirely.
      const key = entry.name.toLowerCase().replace(/\s+/g, ' ').trim()
      const prev = staffIndex.get(key)
      // The campus summary chunk parses to a vaguer campus than the per-category
      // chunk, and the card reads "Role · Campus" — prefer the specific one.
      if (!prev || (entry.campus && !prev.campus)) staffIndex.set(key, entry)
    }
  }

  // A staff question is really a database lookup wearing a sentence — the name,
  // role, campus and email are all sitting in the retrieved chunks. When the
  // model can't be reached, answer those directly instead of shrugging.
  function answerFromData(): string | null {
    if (!personName && !(STAFF_QUERY_RE.test(query) && roleTokens.length)) return null

    const matches: StaffCard[] = []
    for (const entry of staffIndex.values()) {
      if (wantCampus && entry.campus && entry.campus !== wantCampus) continue
      const byName = personName && entry.name.toLowerCase().includes(personName.toLowerCase())
      const byRole = !personName && roleTokens.every((t: string) => {
        const r = entry.role.toLowerCase()
        return r.includes(t) || r.includes(stem(t))
      })
      if (byName || byRole) matches.push(entry)
    }
    if (!matches.length || matches.length > 8) return null

    const lines = matches.map(m => {
      const where = m.campus ? ` at ${m.campus}` : ''
      return `- **${m.name}** — ${m.role}${where}${m.email ? ` — ${m.email}` : ''}`
    })
    return `${lines.join('\n')}\n\n*(Straight from the staff directory — the assistant is temporarily unavailable, so this is the raw listing rather than a written answer.)*`
  }

  function cardsNamedIn(answer: string): StaffCard[] {
    if (!answer.trim() || !staffIndex.size) return []
    const lower = answer.toLowerCase()
    const found: Array<{ card: StaffCard; at: number }> = []
    for (const card of staffIndex.values()) {
      let at = lower.indexOf(card.name.toLowerCase())
      if (at < 0) {
        // Answers refer to staff the way parents do — "Mrs. Heeter", no first name
        const last = card.name.trim().split(/\s+/).pop() ?? ''
        if (last.length > 2) {
          const m = new RegExp(`\\b(?:mr|mrs|ms|miss|dr|coach)\\.?\\s+${last.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\b`, 'i').exec(answer)
          if (m) at = m.index
        }
      }
      if (at >= 0) found.push({ card, at })
    }
    return found.sort((a, b) => a.at - b.at).slice(0, MAX_STAFF_CARDS).map(f => f.card)
  }

  // Context budget. Questions were averaging 21k input tokens because whole
  // chunks went to the model untouched — the GoBound "Upcoming" chunk alone is
  // ~78k characters of every practice for every team, so any sports question
  // paid ~21k tokens for it before a word was written. Chunks are now trimmed to
  // the part that can actually answer the question: the named sport, upcoming
  // dates rather than ones already past, and the lines that share words with the
  // question. scripts/measure-context.mjs asserts the answer-bearing facts
  // survive each trim, which is what keeps this from quietly degrading answers.
  const CONTEXT_CHAR_BUDGET = 30_000
  const CHUNK_CHAR_CAP = 5_000
  const MONTHS_SHORT = ['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec']

  // "[Football JH B (Boys)] Thu, Jul 23, 2026, 7:00 PM: …"
  function lineDate(line: string): Date | null {
    const m = line.match(/\b([A-Z][a-z]{2})[a-z]*\s+(\d{1,2}),\s*(20\d{2})\b/)
    if (!m) return null
    const mi = MONTHS_SHORT.indexOf(m[1].toLowerCase())
    if (mi < 0) return null
    return new Date(Number(m[3]), mi, Number(m[2]))
  }

  const contextTerms = query.toLowerCase().replace(/[^a-z0-9\s]/g, ' ').split(/\s+/)
    .filter((t: string) => t.length > 2 && !STAFF_STOPWORDS.has(t))

  function trimChunk(content: string, cap: number): string {
    const clean = content.replace(/\s*\[photo:[^\]]+\]/g, '')
    if (clean.length <= cap) return clean

    const lines = clean.split('\n')
    const header = lines[0] ?? ''
    let body = lines.slice(1)

    // A question about one sport doesn't need every other team's practices
    if (matchedSport) {
      const sportLines = body.filter(l => hasTerm(l, matchedSport))
      if (sportLines.length) body = sportLines
    }

    // Yesterday's practice can't be the answer to "when is the next game"
    const yesterday = new Date(now.getFullYear(), now.getMonth(), now.getDate() - 1)
    const upcoming = body.filter(l => {
      const d = lineDate(l)
      return !d || d >= yesterday
    })
    if (upcoming.length) body = upcoming

    let out = [header, ...body].join('\n')
    if (out.length <= cap) return out

    // Still too big: keep the lines that share words with the question, in order
    const scored = body.map((line, i) => {
      const l = line.toLowerCase()
      return { i, line, score: contextTerms.reduce((s: number, t: string) => s + (l.includes(t) ? 1 : 0), 0) }
    })
    const keep = scored.slice().sort((a, b) => b.score - a.score || a.i - b.i)
    const chosen: typeof keep = []
    let used = header.length
    for (const s of keep) {
      if (used + s.line.length + 1 > cap) continue
      chosen.push(s)
      used += s.line.length + 1
    }
    chosen.sort((a, b) => a.i - b.i)
    out = [header, ...chosen.map(c => c.line)].join('\n')
    if (chosen.length < body.length) out += `\n… (${body.length - chosen.length} more entries not shown)`
    return out
  }

  const contextParts: string[] = []
  let budgetLeft = CONTEXT_CHAR_BUDGET
  for (const [i, c] of merged.entries()) {
    if (budgetLeft <= 0) break
    const trimmed = trimChunk(c.content, Math.min(CHUNK_CHAR_CAP, budgetLeft))
    budgetLeft -= trimmed.length
    contextParts.push(`[Source ${i + 1}: ${c.title} (${c.url})]\n${trimmed}`)
  }
  const context = contextParts.join('\n\n---\n\n')

  /* Which pages to put under the answer.
   *
   * This took the four highest-scoring chunks, which sounds right and isn't,
   * because `similarity` is a constant on any keyword-anchored chunk. Asked
   * "who is the football coach", the app answers correctly — Justin Rich,
   * jrich@asd20.org — and then cited "TCA Athletics — Upcoming" and three more
   * GoBound calendar links, because those carry a stamped 0.90 and win every
   * slot. The one page that actually had the coach on it, /hs-sports/football,
   * was not among them. A parent clicking through to check finds a schedule.
   *
   * So the citations are chosen after the answer exists, from what the answer
   * visibly used: emails, names, numbers and other distinctive terms that
   * appear in both. A chunk that contributed a fact gets credited for it; a
   * chunk that merely ranked highly does not.
   */
  const STOP = new Set([
    'the', 'and', 'for', 'are', 'with', 'that', 'this', 'from', 'have', 'has', 'his', 'her', 'their',
    'you', 'your', 'not', 'but', 'all', 'any', 'can', 'will', 'they', 'them', 'been', 'were', 'was',
    'tca', 'school', 'classical', 'academy', 'titans', 'student', 'students', 'more', 'here', 'each',
  ])

  /* Distinctive terms in a piece of text, weighted by how much a match means.
   *
   * An email or a time in common is near-proof that a chunk is where a fact
   * came from; a shared ordinary word is barely evidence at all. Unweighted,
   * "what is the dress code" cited a 6th grade supply list, which genuinely
   * shares words like shoes and shirt with a uniform policy and contributed
   * nothing to the answer.
   */
  const HARD_TERM_WEIGHT = 6

  function evidenceTerms(text: string): Map<string, number> {
    const terms = new Map<string, number>()
    const hard = (t: string) => terms.set(t, HARD_TERM_WEIGHT)
    for (const m of text.matchAll(/[\w.+-]+@[\w.-]+\.\w+/g)) hard(m[0].toLowerCase())
    for (const m of text.matchAll(/\b\d{1,2}:\d{2}\s*(?:am|pm)?\b/gi)) hard(m[0].toLowerCase().replace(/\s+/g, ''))
    for (const m of text.matchAll(/\$\s?\d[\d,]*(?:\.\d{2})?/g)) hard(m[0].replace(/\s/g, ''))
    for (const m of text.matchAll(/\b[A-Za-z][A-Za-z'-]{3,}\b/g)) {
      const w = m[0].toLowerCase()
      if (!STOP.has(w) && !terms.has(w)) terms.set(w, 1)
    }
    return terms
  }

  const dedupeSources = (chunks: Chunk[]) => {
    const seen = new Set<string>()
    const out: { url: string; title: string }[] = []
    for (const c of chunks) {
      if (seen.has(c.url)) continue
      seen.add(c.url)
      out.push({ url: c.url, title: c.title })
      if (out.length === 4) break
    }
    return out
  }

  // Used when the answer never arrives (generation failed) and as the floor when
  // nothing overlaps — a paraphrased answer can legitimately share few terms.
  const fallbackSources = dedupeSources(merged.filter((c: Chunk) => c.similarity >= 0.50))

  function sourcesFor(answer: string): { url: string; title: string }[] {
    const answerTerms = evidenceTerms(answer)
    if (answerTerms.size < 3) return fallbackSources

    let totalWeight = 0
    for (const w of answerTerms.values()) totalWeight += w

    const scored = merged
      .map((c: Chunk) => {
        const chunkTerms = evidenceTerms(c.content)
        let hit = 0
        for (const [term, weight] of answerTerms) if (chunkTerms.has(term)) hit += weight
        // The share of the answer, by weight, that this chunk can account for.
        return { c, score: hit / totalWeight }
      })
      .filter(s => s.score > 0.12)
      .sort((a, b) => b.score - a.score)

    return scored.length ? dedupeSources(scored.map(s => s.c)) : fallbackSources
  }

  // Inspect what a question would cost and what it would be answered from,
  // without spending a single answer token. Secret-gated; used by
  // scripts/measure-context.mjs to prove a context trim didn't drop the facts.
  if (debug && secretMatches(req.headers.get('x-crawl-secret'), process.env.CRAWL_SECRET)) {
    const chars = context.length
    return Response.json({
      query,
      chunkCount: merged.length,
      contextChars: chars,
      estInputTokens: Math.round(chars / 3.7) + 1400, // ≈ context + system prompt
      chunks: merged.map((c: Chunk) => ({
        title: c.title,
        url: c.url,
        similarity: Number(c.similarity?.toFixed(3) ?? 0),
        chars: c.content.length,
      })),
      context,
    })
  }

  /* Build conversation messages for Anthropic.
   *   Prior turns: clean query + answer text (no context injection)
   *   Current turn: query + fresh context
   *
   * The last prior turn carries a cache breakpoint. Prior turns are identical
   * on every request of a conversation — the retrieved context is only ever
   * attached to the *current* turn — so `system + history` is a stable prefix
   * that grows by one turn each time, and each turn reads what the previous
   * one wrote. Follow-ups arrive seconds apart, well inside the 5-minute TTL.
   *
   * This is the breakpoint that matters on the Haiku path: the system prompt
   * alone (1,534 tokens) is under Haiku's 4,096-token floor, but system plus a
   * few turns of history clears it. Multi-turn threads were also the expensive
   * ones — the worst logged query was a five-turn conversation re-sending its
   * whole history at 126,750 input tokens. */
  const anthropicMessages: {
    role: 'user' | 'assistant'
    content: string | { type: 'text'; text: string; cache_control?: { type: 'ephemeral' } }[]
  }[] = [
    ...history.map((turn, i) =>
      i === history.length - 1
        ? {
            role: turn.role,
            content: [
              { type: 'text' as const, text: turn.content, cache_control: { type: 'ephemeral' as const } },
            ],
          }
        : turn
    ),
    {
      role: 'user' as const,
      // Deliberately NOT cached: the context is freshly retrieved per question,
      // so a breakpoint here would write an entry no later request could read.
      content: `Context from TCA website:\n\n${context}\n\nQuestion: ${query}`,
    },
  ]

  const systemPrompt = `You are a helpful assistant for TCA (The Classical Academy) in Colorado Springs. Be warm and conversational — like a knowledgeable friend who knows TCA inside and out. You do not know who the user is or which student they have. Never say "your team", "your student", "your child", or "your next game" unless they've explicitly told you their grade or campus in this conversation. Always refer to teams by name: "TCA football", "the JH A team", "TCA Volleyball Varsity", etc. If two calendar sources show different times for the same event, say so: "GoBound shows 8:30 AM; TeamReach lists it as tentative at 9:00 AM — confirm with the coach."

HARD RULE: Do not ask follow-up questions. Ever. Do not end with "Is there anything else I can help you with?", "Is that who you're looking for?", "Does that help?", or any question. Answer, then stop.

TCA campuses: Central Elementary, East Elementary, and North Elementary (K–6); one Junior High (grades 7–8); one High School (grades 9–12); plus College Pathways. There is only one JH and one HS — so questions about 7th/8th graders are automatically JH, 9th–12th are automatically HS. Elementary questions may need campus clarification (Central, East, or North).

Synonyms — treat all of these as identical: "Junior High" = "JH" = "middle school" = "7th grade" = "8th grade" = "seventh grade" = "eighth grade" = "grades 7-8". If a parent says "middle school" or "my 7th grader," that means Junior High. Carry campus/school context between turns: if the prior question was about Junior High, assume the next question is also about Junior High unless stated otherwise.

High school grade levels: 9th = Freshman, 10th = Sophomore, 11th = Junior, 12th = Senior. Understand and use these terms naturally — if a parent says "my freshman" treat it as 9th grade/High School, "my sophomore" as 10th grade/High School, etc.

Be smart about context: sports (football, basketball, soccer, wrestling, cheer, etc.), athletics schedules, and team-specific questions only apply to Junior High and High School — never mention elementary in those answers unless the parent specifically brings it up. Literacy testing (DIBELS, reading assessments, oral reading fluency, etc.) only applies to elementary campuses (Central, East, North) — never reference it for Junior High or High School. If the parent has a 5th grader and asks about football, answer for JH/HS and don't add a note about the elementary student.

Current school year is ${schoolYearLabel}. A date is "past" only if it is before TODAY's date — today's events are current and valid to cite regardless of month. Never dismiss July or August events as "summer break" — TCA runs athletics, camps, and activities year-round including summer. If you only have a past date for a recurring annual event, say "Last year it was [date] — the ${schoolYearLabel} date hasn't been posted yet." Never call a future date "already passed."

Calendar data is authoritative: if the calendar context includes a month's events and a specific date in that month is NOT listed as a closure, no-school day, or break, then school IS in session on that date. You do not need to say "I'm not sure" — if you have the month's data and the date isn't listed as a closure, confidently say school is in session. Only express uncertainty if you don't have that month's calendar data at all.

Sports schedule accuracy rule: The schedule data comes from two sources. GoBound ("TCA Athletics — …" chunks) carries games, meets and competitions, and now also carries practices for many teams. TeamReach ("TCA HS Football — …", "TCA JH Football — …" chunks) is a coach's own feed, connected for a few teams only, and carries practices, weights and training in more detail. Rules:
1. For a GAME or competition time, GoBound wins — if TeamReach gives a different time or says "tentative," defer to GoBound.
1a. For a PRACTICE, check BOTH sources. GoBound lists practices for many teams and TeamReach adds detail for the few teams it covers, so a practice may appear in either or both. Answer from whichever chunks actually show practices for the team asked about, and if both show the same practice at different times, say so and name both. Never answer "there are no practices" because one source does not show any — a source that has no entry for a team is silent, not authoritative. If neither source shows a practice, say none are listed for that team rather than saying none exist.
1b. A question about "football" with no level given means the high school team. Answer for HS first; mention JH only if you have nothing for HS or the parent asked for it.
2. When asked about a specific level, ONLY list dates/times from events tagged with that EXACT level.
3. [Football C-Squad (Boys)] events are C-Squad only. They are not Varsity. Never include them in a Varsity answer.
4. If no upcoming events appear in context, link to https://gobound.com/co/schools/theclassahs/calendar?v=list — never fabricate URLs.
5. Never extrapolate, assume, or pattern-match from other levels or days. Only cite explicit events.
6. If asked whether TCA has a specific sport and no schedule data exists in context, do NOT say the sport doesn't exist — say no events are showing yet and link to https://gobound.com/co/schools/theclassahs/calendar?v=list to confirm.

Answer style:
- Lead with the answer. No preamble ("Based on...", "According to...").
- **NEVER end with a question of any kind. The HARD RULE above is absolute — it overrides everything else. When in doubt: answer, then stop.**
- When one word in the question names more than one distinct event, give every one of them with its own date — never pick the one you happened to retrieve first. "Homecoming" is a football game on one night and a dance on another; spirit week is a week of separate events; picture day differs per campus. Answer "the homecoming game is Friday the 25th, the dance is Saturday the 26th", not one of the two as though the other did not exist. A parent who asks about homecoming and is told only about the dance will miss the game.
- When a question could apply to multiple campuses or grade levels with no prior context, list the answer for each one briefly — do not ask which campus. E.g. "School ends at 3:30 PM at all three elementaries (Mon–Thu), 3:00 PM at JH, and 3:10 PM at HS." Asking is never the right move.
- 1–4 sentences for most things. Bullet points only for 3+ distinct items.
- Be direct and specific — "9th graders start on..." or "TCA football opens on..." rather than vague generalizations.
- If something's not in the context, say so in one sentence and link them somewhere useful — but the link must match what they asked about. A date question gets the [TCA calendar](https://www.tcatitans.org/calendar); a person question gets the [staff directory](https://www.tcatitans.org/family/staff-directory); a sports question gets [GoBound](https://gobound.com/co/schools/theclassahs/calendar?v=list). Sending someone asking about a dance to the staff directory is worse than sending them nowhere — it reads as though you didn't understand the question.
- Never offer more than one fallback link. Two links to "confirm the date" is a shrug, not an answer.
- Always include a direct URL as a markdown link when referencing a specific page or form.
- For lists (spelling words, supply lists, etc.): reproduce them completely, don't summarize.
- You're in a conversation — use prior context naturally. **Conversation context beats profile**: if the prior turn mentioned a specific campus or school, assume that campus for follow-up questions without clarifying.`

  /* The system prompt, split so the stable part can be cached.
   *
   * Prompt caching is a prefix match: the cache key is the exact bytes up to
   * the breakpoint, and anything that changes invalidates everything after it.
   * The clock below used to sit in the middle of this prompt —
   * "Current time is approximately 3:47 PM" — which rewrote the prefix every
   * minute. Marking that prompt as cacheable would have bought a 1.25x write
   * on nearly every request and almost never a read.
   *
   * So the volatile line moves to its own block after the breakpoint. Blocks
   * render in order, so everything before `cache_control` is the cached
   * prefix and the date/time rides behind it, uncached and free to change.
   *
   * `schoolYearLabel` stays inside the cached block deliberately: it changes
   * once a year, and a yearly invalidation is not worth a second block. */
  /* "This week" and "next week", worked out here rather than left to the model.
   *
   * Asked "when is football practice next week" on Saturday 1 August, the app
   * answered from 10 August. The practices for 3-7 August were in the context —
   * retrieval was fine — it simply resolved "next week" to the wrong seven days.
   * A parent asking on a Saturday means the week starting in two days, and
   * saying so with dates removes the judgement call entirely.
   *
   * Weeks run Monday to Sunday, so on a Saturday "this week" is the one now
   * ending and "next week" begins on the Monday two days out.
   */
  const denverToday = new Date(now.toLocaleString('en-US', { timeZone: 'America/Denver' }))
  const dayOfWeek = (denverToday.getDay() + 6) % 7 // 0 = Monday
  const weekStart = new Date(denverToday)
  weekStart.setDate(weekStart.getDate() - dayOfWeek)
  const span = (start: Date, days: number) => {
    const a = new Date(start)
    const b = new Date(start)
    b.setDate(b.getDate() + days)
    const f = (d: Date) => d.toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' })
    return `${f(a)} through ${f(b)}`
  }
  const nextWeekStart = new Date(weekStart)
  nextWeekStart.setDate(nextWeekStart.getDate() + 7)

  /* The complete set of dated events inside the week the parent asked about,
   * computed here in code rather than left to the model to work out.
   *
   * Measured failure this was built for: asked "is there volleyball practice
   * this week", the app answered five times out of five with a JH Volleyball
   * practice on Wednesday August 7 and Thursday August 8, 3:30-5:30 PM at the
   * North Campus Auxiliary Gym. A scan of all 2,295 chunks in every source
   * found no volleyball entry on either date. What exists is a real recurring
   * Wednesday/Thursday practice starting August 12 — the model took the
   * pattern and slid it back a week to fit the question. Team, time and
   * location were all correct, which is exactly what makes it dangerous: a
   * parent would have driven their child to an empty gym.
   *
   * Prose did not fix it. An explicit "check each date against the range"
   * instruction made it worse, 1-in-3 correct to 0-in-5, and the model started
   * echoing the phrasing of the example in the rule. So the range check moves
   * out of the prompt and into code: filter the context to the asked-about
   * dates and hand over the result as a closed list. There is then nothing to
   * extrapolate from, because the events of neighbouring weeks are not in
   * front of it when it answers.
   *
   * Dates here are Denver wall-clock components, so they are read with the
   * local getters — denverToday already holds the shifted values, and applying
   * a timeZone again would shift them twice. */
  const ymd = (d: Date) =>
    `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`
  const shift = (d: Date, days: number) => { const x = new Date(d); x.setDate(x.getDate() + days); return x }

  const RANGES: Record<string, () => [Date, Date]> = {
    'this week': () => [weekStart, shift(weekStart, 6)],
    'next week': () => [nextWeekStart, shift(nextWeekStart, 6)],
    'this weekend': () => [shift(weekStart, 5), shift(weekStart, 6)],
    'today': () => [denverToday, denverToday],
    'tonight': () => [denverToday, denverToday],
    'tomorrow': () => [shift(denverToday, 1), shift(denverToday, 1)],
  }
  const askedRange = Object.keys(RANGES).find(k => new RegExp(`\\b${k}\\b`, 'i').test(query))

  let rangeNote = ''
  /* Only meaningful if a dated schedule actually came back. "No events in
   * range" is evidence when the calendar is in front of us and that week is
   * empty; it is worthless when retrieval returned no calendar at all, and
   * asserting it then produces a confident "nothing is on today" over a day
   * with eight events — which is what the first version of this did to "what
   * is happening today at TCA". Absence from the retrieved context is not
   * absence from the schedule. */
  const contextHasSchedule = /^\d{4}-\d{2}-\d{2}/m.test(context)
  if (askedRange && contextHasSchedule) {
    const [from, to] = RANGES[askedRange]()
    const lo = ymd(from), hi = ymd(to)
    const inRange = [...new Set(
      context.split('\n')
        .map(l => l.trim())
        .filter(l => { const d = l.match(/^(\d{4}-\d{2}-\d{2})/)?.[1]; return d !== undefined && d >= lo && d <= hi })
    )].sort()

    const label = `${askedRange} (${lo} to ${hi})`
    rangeNote = inRange.length
      // Capped so a busy week cannot crowd out the retrieved pages themselves.
      ? `Dated events in your context for ${label} — this list was computed from that context and is COMPLETE:\n${inRange.slice(0, 60).join('\n')}\n\nAnswer only from these lines. If the team or activity the parent asked about does not appear above, then nothing is scheduled for it in that range and you must say so plainly. Never move an event from another week onto these dates, and never combine a date from this list with a time from elsewhere.`
      : `The schedule data you were given contains NO events for ${label}. Say plainly that nothing is listed for that period in the schedules you can see. Do not construct an event for it from a recurring pattern in another week — if you name the next scheduled dates instead, label them with the week they are actually in.`
  }

  /* Which teams have a TeamReach feed connected.
   *
   * TeamReach groups are joined with a per-team code, so the only feeds we can
   * have are the ones a single parent could join — currently HS and JH
   * Football.
   *
   * This used to be the whole practice story, and the prompt said so. It is not
   * any more: GoBound now carries 277 distinct practice entries across eight
   * sports, added by the school over the summer. The first version of this note
   * asserted there was no practice data for any other sport, which was already
   * false when it was written — the app answered a volleyball practice question
   * correctly straight from GoBound while the note claimed it could not.
   *
   * So this names the TeamReach feeds as *additional* detail rather than as the
   * boundary of what is known. Read from the corpus rather than hardcoded, so a
   * feed added or dropped does not leave a false claim behind — which is the
   * failure this whole note exists to prevent. */
  let coveredTeams: string[] = []
  try {
    const { data: trRows } = await supabase
      .from('page_chunks')
      .select('title')
      .ilike('url', '%teamreach%')
      .limit(200)
    coveredTeams = [...new Set((trRows ?? [])
      .map(r => String(r.title ?? '').split('—')[0].trim())
      .filter(Boolean))].sort()
  } catch { /* leave empty — the rule below then says we have no practice feeds */ }

  const practiceNote = `Practice-schedule coverage: GoBound lists practices for many TCA teams, and is the broadest practice source — always check the GoBound chunks for a practice question, whatever the sport.${coveredTeams.length ? ` In addition, a coach's TeamReach feed is connected for these teams only: ${coveredTeams.join(', ')}; for those, TeamReach may carry detail or last-minute changes GoBound does not.` : ''} If a practice question turns up nothing for the team asked about, say that no practices are currently listed for that team, point to GoBound, and suggest the coach or athletics office — never say or imply the team has no practices, and never answer from a different team's schedule.`

  /* Say where athletics answers come from and what that source does not cover.
   *
   * TCA moved athletics onto GoBound and is still filling it in — rosters and
   * stats are empty, and schedules populate as the season nears. An answer
   * drawn from a half-filled source reads exactly like an answer drawn from a
   * complete one, and the parent has no way to tell which they got.
   *
   * Scoped to thin or empty athletics answers on purpose. A caveat attached to
   * every answer is noise that gets skimmed past, and it would undercut the
   * many answers that are complete and correct. */
  const coverageNote = `${practiceNote}

Athletics data provenance: game and competition schedules come from GoBound, which is the school's system and shows only what TCA has entered so far — it is still being populated for the 2026-27 year, and rosters and statistics are largely empty. When an athletics answer is thin, partial, or turns up nothing, say which source you looked in and that it only reflects what the school has published there so far, then point to https://gobound.com/co/schools/theclassahs/calendar?v=list. Do not present an empty or sparse result as if it were the complete picture, and do not treat missing data as evidence that an event, team or sport does not exist. When you do have the answer, just give it — no caveat needed.`

  const systemBlocks = [
    { type: 'text' as const, text: systemPrompt, cache_control: { type: 'ephemeral' as const } },
    {
      type: 'text' as const,
      text: `Today is ${new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric', timeZone: 'America/Denver' })}. Current time is approximately ${new Date().toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit', timeZone: 'America/Denver' })} Mountain Time.
"This week" means ${span(weekStart, 6)}. "Next week" means ${span(nextWeekStart, 6)}. Use those exact ranges — do not work them out again — and when a question uses either phrase, name the dates you are answering for so the parent can check you meant the same week they did.

Match the team as written when reading schedule lines: "Junior Titan Volleyball Camp" is not a JH Volleyball practice, "HS- Boys Basketball" is not volleyball, and a tryout or off-season entry is not a regular practice. Inventing a plausible practice time is the worst failure you can make — a parent will drive their child to it.${rangeNote ? `\n\n${rangeNote}` : ''}

${coverageNote}`,
    },
  ]

  /* Two different numbers that were being conflated.
   *
   * `similarity` on a chunk serves double duty. For vector hits it is a real
   * cosine score from match_chunks. For keyword-anchored hits it is a constant
   * this route stamps on to force the chunk up the ordering — 0.90 for the
   * GoBound athletics anchor, 0.82 for a sport-specific one, 0.72, 0.70, 0.65,
   * 0.60 elsewhere. As a *ranking* hint that is fine and deliberate.
   *
   * The bug was reading the same field back as a *measurement*. topSimilarity is
   * the max across merged chunks, so any query that tripped the athletics anchor
   * reported 0.90 regardless of how well anything actually matched, while a
   * query that missed the anchors reported its true ~0.55. The dashboard's
   * "thin" count and the Sonnet routing decision both keyed off that, so the
   * same number meant different things depending on which path a query took —
   * which is why logged medians (0.65-0.72) and directly measured cosines
   * (0.547-0.608) disagreed.
   *
   * `vectorTopSimilarity` is the honest one: the best real cosine, taken before
   * the keyword chunks are merged in. That is what gets logged.
   */
  const vectorTopSimilarity = (chunks ?? []).reduce(
    (max: number, c: Chunk) => Math.max(max, c.similarity),
    0
  )

  // Routing deliberately still uses the merged value, including the synthetic
  // anchors. Those constants encode "a keyword anchor fired, so we have a
  // confidently relevant chunk" — which is genuinely a reason not to escalate.
  // Switching this to the vector score would silently move a chunk of traffic
  // onto Sonnet at 3x cost, so it waits until the newly-honest logged numbers
  // show where the line actually belongs.
  const topSimilarity = merged.reduce((max: number, c: Chunk) => Math.max(max, c.similarity), 0)

  // Escalate to Sonnet only on the harder cases — weak retrieval match (model has to
  // synthesize/hedge across thin or conflicting sources) or a long multi-turn thread
  // (more context to track correctly). Everything else stays on Haiku.
  //
  // Worth knowing for caching: the minimum cacheable prefix is model-specific —
  // 1,024 tokens on Sonnet 5, but 4,096 on Haiku 4.5. This system prompt measures
  // 1,534 tokens, so it caches on the Sonnet path and is silently too short to
  // cache on the Haiku one (no error — just no cache entry). The breakpoint on
  // the last history turn below is what earns a hit on Haiku, once a conversation
  // has grown past that floor.
  const isHardCase = topSimilarity < 0.55 || history.length >= 6
  const MODEL = isHardCase ? 'claude-sonnet-5' : 'claude-haiku-4-5-20251001'

  // Stream the response
  const readableStream = new ReadableStream({
    async start(controller) {
      // Citations are sent once the answer exists — see sourcesFor(). The client
      // stores them whenever they arrive and the panel renders under the answer,
      // so this reads as the citations settling after the text, rather than four
      // links sitting there while the answer is still being written.
      let sources = fallbackSources

      // Cards follow the answer as it's written: the moment the model names
      // someone, their face appears. Re-sent only when the set actually changes.
      let cardSignature = ''
      const pushCards = () => {
        const staffCards = cardsNamedIn(answerText)
        const signature = staffCards.map(c => c.name).join('|')
        if (signature === cardSignature) return
        cardSignature = signature
        if (staffCards.length) controller.enqueue(send({ type: 'staffCards', staffCards }))
      }

      let answerText = ''
      let failure = ''
      let usage: {
        input_tokens?: number
        output_tokens?: number
        cache_creation_input_tokens?: number
        cache_read_input_tokens?: number
      } = {}
      try {
        const stream = anthropic.messages.stream({
          model: MODEL,
          max_tokens: 1024,
          system: systemBlocks,
          messages: anthropicMessages,
        })

        for await (const event of stream) {
          if (
            event.type === 'content_block_delta' &&
            event.delta.type === 'text_delta' &&
            event.delta.text
          ) {
            answerText += event.delta.text
            controller.enqueue(send({ type: 'text', text: event.delta.text }))
            pushCards()
          }
          if (event.type === 'message_delta' && event.usage) {
            usage = { ...usage, output_tokens: event.usage.output_tokens }
          }
          if (event.type === 'message_start') {
            // All three, not just input_tokens: with caching on, input_tokens is
            // the *uncached remainder*. Total prompt size is the sum, and the
            // cached portions are still billed — 1.25x to write, 0.1x to read.
            usage = {
              ...usage,
              input_tokens: event.message.usage.input_tokens,
              cache_creation_input_tokens: event.message.usage.cache_creation_input_tokens ?? 0,
              cache_read_input_tokens: event.message.usage.cache_read_input_tokens ?? 0,
            }
          }
        }
      } catch (e) {
        // A parent should never see an API error, and definitely never a billing
        // one — this used to surface "Your credit balance is too low to access
        // the Anthropic API" verbatim in the answer card. Retrieval already
        // succeeded, so fall back to handing them the pages it found.
        failure = String(e)
        console.error('answer generation failed:', failure)
        // Retrieval doesn't touch Anthropic, so the data is sitting right here.
        // For the questions we can answer straight from it — who someone is, how
        // to reach them — compose the answer ourselves rather than apologising.
        const fromData = answerFromData()
        const fallback = fromData
          ?? (sources.length
            ? "I can't write a full answer right now — the assistant is temporarily unavailable. The links below should have what you're looking for."
            : "I can't answer right now — the assistant is temporarily unavailable. Please try again in a few minutes, or visit [tcatitans.org](https://www.tcatitans.org).")
        if (!answerText) {
          answerText = fallback
          controller.enqueue(send({ type: 'text', text: fallback }))
          pushCards()
        }
        if (!fromData) controller.enqueue(send({ type: 'error', message: 'assistant unavailable' }))
      }

      sources = sourcesFor(answerText)
      controller.enqueue(send({ type: 'sources', sources }))

      // Only a real generation is worth caching — never an outage message, and
      // never a follow-up whose meaning depends on the turn before it.
      if (cacheable && !failure && answerText.trim().length > 20) {
        const ttl = VOLATILE_RE.test(query) ? VOLATILE_TTL : STABLE_TTL
        cache.set(cacheKey, {
          answer: answerText,
          sources,
          staffCards: cardsNamedIn(answerText),
          model: MODEL,
        } satisfies CachedAnswer, { ttl, tags: ['answers'], name: 'tca-answer' })
          .catch(() => { /* cache write failed — the answer still went out */ })
      }

      // Log query + answer (fire and forget — never blocks the response).
      // A failed generation is logged as its own model so an outage shows up on
      // the dashboard instead of looking like a normal answer.
      logQuery(supabase, {
        query: loggedQuery,
        had_results: true,
        source_count: merged.length,
        top_similarity: vectorTopSimilarity,
        model: failure ? `${MODEL}-failed` : MODEL,
        latency_ms: Date.now() - requestStart,
        answer: answerText,
        sources,
        cache_hit: false,
        input_tokens: usage?.input_tokens ?? null,
        output_tokens: usage?.output_tokens ?? null,
        cache_creation_input_tokens: usage?.cache_creation_input_tokens ?? null,
        cache_read_input_tokens: usage?.cache_read_input_tokens ?? null,
      })

      controller.enqueue(send({ type: 'done' }))
      controller.close()
    },
  })

  return new Response(readableStream, {
    headers: { 'Content-Type': 'application/x-ndjson' },
  })
}
